openapi: 3.0.3
info:
  title: Backend for Qred
  version: 1.0.11
servers:
  - url: http://localhost:8080/api
tags:
  - name: company
    description: Operations about company
  - name: activation
    description: Operations for card activation
  - name: transaction
    description: Operations about transaction
paths:
  /company:
    get:
      tags:
        - company
      summary: Get company details
      operationId: getCompany
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
  /transactions:
    get:
      tags:
        - transaction
      summary: Fetch all transactions for the company
      operationId: getTransactions
      parameters:
        - name: offset
          in: query
          schema:
            type: integer
            example: 0
        - name: limit
          in: query
          schema:
            type: integer
            example: 10
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionsResponse'
  /activated-card:
    post:
      tags:
        - activation
      summary: Activate the card
      operationId: activateCard
      responses:
        '200':
          description: Card activated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Card'

components:
  schemas:
    Company:
      type: object
      properties:
        id:
          type: integer
          example: 10
        name:
          type: string
          example: "Company AB"
        card:
          $ref: '#/components/schemas/Card'
    Card:
      type: object
      properties:
        id:
          type: integer
          example: 10
        credit_limit:
          type: integer
          example: 10000
        balance:
          type: integer
          example: 5457
        card_url:
          type: string
          format: uri
          example: "http://example.com"
        status:
          type: string
          enum:
            - ACTIVE
            - BLOCKED
    Transaction:
      type: object
      properties:
        id:
          type: integer
          example: 18867
        description:
          type: string
          example: "Spent on amazon"
        amount:
          type: integer
          description: "Amount in cents"
          example: 3550
          format: currency
        transaction_date:
          type: string
          format: date-time
          example: "2023-03-20T09:12:28Z"
    TransactionsResponse:
      type: object
      properties:
        count:
          type: integer
          example: 50
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
